FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG PUBLIC_API_BASE_URL="https://api-spanish.tonymuzo.dev"
ENV PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
RUN npm run build

FROM node:20-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY cloudrun-static-server.mjs ./cloudrun-static-server.mjs
CMD ["node", "cloudrun-static-server.mjs"]
